[package]
name = "example-api"
version = "0.25.0-api"
authors = ["shun <shun.fix9@gmail.com>"]
edition = "2018"
build = "api/setup/build.rs"

[dependencies]
getto-application = { path = "api/vendor/getto-application" }
aws-cloudfront-cookie = { path = "api/vendor/aws-cloudfront-cookie" }
actix-web = "3"
actix-cors = "0.5"
protobuf = "2"
base64 = "0.13"
jsonwebtoken = "7"
argon2 = "0.2"
chrono = "0.4"
time = "0.2"
uuid = { version = "0.8", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
protobuf-codegen-pure = "2"
