/* eslint-disable */
module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    testRegex: "/test(\\.[^/]*)?\\.ts$",
    rootDir: "../..",
    collectCoverage: true,
    collectCoverageFrom: [
        "**/*.ts",
        "!ui/**",
        "!**/x_*/**",
        "!**/y_*/**",
        "!src/z_vendor/base64/**",
        "!src/z_vendor/getto-application/action/worker/**",
        "!src/z_vendor/getto-application/board/kernel/convert.ts",
        "!src/z_vendor/getto-application/docs/helper.ts",
        "!src/z_vendor/getto-css/**",
        "!src/z_vendor/getto-table/**",
        "!src/z_vendor/protobuf/**",
        "!**/test.ts",
        "!**/test_helper.ts",
        "!**/menu/**",
        "!**/init/**",
        "!**/init.ts",
        "!**/view.ts",
        "!**/infra.ts",
        "!**/mock.ts",
        "!**/docs.ts",
        "!**/site.ts",
    ],
    coverageThreshold: {
        global: {
            functions: 100,
        },
    },
    coverageDirectory: "ui/public/dist/coverage/ui",
}
